name: enviromentFlooding
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - geopandas
  - cartopy>=0.21
  - notebook
  - rasterio
  - pyepsg
  - folium
  - rasterstats
  - pandas
  - Shapely
  - Fiona
  - pyproj
  - NumPy
  - six
  - ipython